version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: jobsdb
      POSTGRES_USER: jobsuser
      POSTGRES_PASSWORD: jobspass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobsuser -d jobsdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://jobsuser:jobspass@db:5432/jobsdb
      JWT_SECRET: supersecret_change_me
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  dbdata:
